travis:
  secure:
    BINSTAR_TOKEN: doJqjOUaECre/SgtntRmKZxxZsohPPOur+JuZLqvqD4TfhHl/GxsT/oLTZA1u2Vo7zri1VDquzViuOxUpKRL6c2+BZwV1bFNCUOiRLVVcCl0sDy6OmIXQ4D5ss1VbcQkdbMUon2vieh3FvNmBm5rYbe+XEC2jTyUgdXLa7vlOQS1TOdeuHP3pZHki0pq/Ovf1pyqcj0Dq5lsCvhwcnKUabIPtgUcGRQbMJ6chuvuj+ACPTiel3F88pHCg7nvgueIQQghLaU1Md7rVYhajLia8CWjuCZ+19ZLHXR91xn4Zl+ZX56x71cp22EQhrZJHTIF6ZE0+ApVoAbxwzYyv2BrAdNu7pMnsgaiEMcXxfLRqyj+tlYVa2fqZh2kYybAm+VO0r+7jlFzr/sINQ4ks37qxLVSLE5+NIh9JPF0ygRL4Bv/sjrPRcsZLnsHnuyxxPlArebdkX/iS9RFxAQwh9NIfxDIEsgjlXBnHAaU/L3ri5m0n+igDZZOGtHeINIrS4aTs0q+ygEjvlqlr35V1its3o8fuoF7rlGEEj7GTpL/S3qsYUetC15W3MRJzfrW534evMOF37fttW27Ec9vJoNjBdcr9lXpWMUcRx0zt5AMKTz7oJPeCGFmQKMgRp1Ap8MryXH/HymBWkWZ/oewRkp06VWbRRcmXsuGib+52eDRha0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1

provider:
  osx: circle

